name: rrhfit_sys32
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_database: ^12.0.2
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  sidebarx: ^0.17.2
  intl: ^0.18.0
  pdf: ^3.11.3
  printing: ^5.11.0
  http: ^1.5.0
  supabase_flutter: ^2.10.3
  file_picker: ^10.3.3
  open_filex: ^4.7.0
  flutter_typeahead: ^5.2.0
  fl_chart: ^1.1.1
  syncfusion_flutter_charts: ^31.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/fittlay.png
    - assets/fonts/Roboto-Regular.ttf